- id: uv-bump-version
  name: uv-bump-version
  description: "Automatically run 'uv version --bump patch' on your project if version is stale"
  entry: uv_bump_version.py
  language: python
  types: [toml]
  files: ^pyproject\.toml$
  args: []
  pass_filenames: false
  additional_dependencies: []
  # additional_dependencies: [tomli]  # Only needed for Python <3.11
  minimum_pre_commit_version: "2.9.2"
