- id: bump-version-if-needed
  name: Bump version with uv if not already bumped
  entry: bump_version_if_needed.py
  language: python
  types: [toml]
  files: ^pyproject\.toml$
  # additional_dependencies: [tomli]  # Only needed for Python <3.11
